apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
namespace: app
images:
- name: registry.gitlab.com/picasso-code/nuxt-js-basic-ssr
  newTag: bb26f865096103e87758991f4f1b91e3eed1fdae
