apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-web-global-staging
  namespace: argocd
spec:
  project: frontend-web-global
  source:
    repoURL: https://github.com/davidsugianto/argocd-demo.git
    targetRevision: master
    path: applications/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true