apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-web-global-production
  namespace: argocd
spec:
  project: frontend-web-global
  source:
    repoURL: https://github.com/davidsugianto/argocd-demo.git
    targetRevision: master
    path: applications/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production-app
  # syncPolicy:
  #   automated:
  #     prune: true
